name: mobile_tracking_location

versioning:
  mode: independent

packages:
  - "data/*"
  - "driver_app/*"
  - "user_app/*"
  - "feature/*"

scripts:
  postclean:
    run: melos run clean:flutter --no-select
    description: Runs "flutter clean" in all Flutter packages

  pubget:
    run: melos exec -c 1 -- "flutter pub get"
    description: Runs "flutter pub get" in all Flutter packages

  generate:all:
    run: melos run pubget && melos run generate:dart && melos run generate:flutter && melos run gen_localize
    description: Build all generated files for Dart & Flutter packages in this project.

  generate:dart:
    run: melos exec -c 1 --depends-on="build_runner" --no-flutter -- "dart run build_runner build --delete-conflicting-outputs --enable-experiment=super-parameters,enhanced-enums"
    description: Build all generated files for Dart packages in this project.

  generate:flutter:
    run: melos exec -c 1 --depends-on="build_runner" --flutter -- "flutter packages pub run build_runner build --delete-conflicting-outputs --enable-experiment=super-parameters,enhanced-enums"
    description: Build all generated files for Flutter packages in this project.

  gen_localize:
    run: melos exec -c 1 --flutter -- "flutter pub run easy_localization:generate -S assets/translations -O lib/translations -o locale_keys.g.dart -f keys"
    description: gen localize keys
    select-package:
      scope: '*feature*'

  clean:flutter:
    run: melos exec -c 4 --fail-fast -- "flutter clean"
    description: Run Flutter clean for a specific package in this project.

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=1.17.0 <3.0.0'