// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArLEghTt9UcXmQA72l0AMJuX8hwe0QWgw',
    appId: '1:309235316858:web:32813ba0e54b8a32d3a3c3',
    messagingSenderId: '309235316858',
    projectId: 'sts-mobile-case-study',
    authDomain: 'sts-mobile-case-study.firebaseapp.com',
    databaseURL: 'https://sts-mobile-case-study-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sts-mobile-case-study.appspot.com',
    measurementId: 'G-K9S5YCHE2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0wD-Fjt2WtFEQ4L1UC1t-9QHzBSmH4SQ',
    appId: '1:309235316858:android:9bd717b330b403d2d3a3c3',
    messagingSenderId: '309235316858',
    projectId: 'sts-mobile-case-study',
    databaseURL: 'https://sts-mobile-case-study-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sts-mobile-case-study.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATOXQWAzUSlI5WlAyJ0ayr-vn38ajModk',
    appId: '1:309235316858:ios:67abf2bac62b8b74d3a3c3',
    messagingSenderId: '309235316858',
    projectId: 'sts-mobile-case-study',
    databaseURL: 'https://sts-mobile-case-study-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sts-mobile-case-study.appspot.com',
    iosClientId: '309235316858-7js5i3htq7nlp4p63umg2l02tna9trf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileTrackingLocation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATOXQWAzUSlI5WlAyJ0ayr-vn38ajModk',
    appId: '1:309235316858:ios:67abf2bac62b8b74d3a3c3',
    messagingSenderId: '309235316858',
    projectId: 'sts-mobile-case-study',
    databaseURL: 'https://sts-mobile-case-study-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sts-mobile-case-study.appspot.com',
    iosClientId: '309235316858-7js5i3htq7nlp4p63umg2l02tna9trf5.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileTrackingLocation',
  );
}
