// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0wD-Fjt2WtFEQ4L1UC1t-9QHzBSmH4SQ',
    appId: '1:309235316858:android:2d8c06fa90349fe2d3a3c3',
    messagingSenderId: '309235316858',
    projectId: 'sts-mobile-case-study',
    databaseURL: 'https://sts-mobile-case-study-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sts-mobile-case-study.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATOXQWAzUSlI5WlAyJ0ayr-vn38ajModk',
    appId: '1:309235316858:ios:a3f2de7775f07ae2d3a3c3',
    messagingSenderId: '309235316858',
    projectId: 'sts-mobile-case-study',
    databaseURL: 'https://sts-mobile-case-study-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sts-mobile-case-study.appspot.com',
    iosClientId: '309235316858-b5pe5tu4pujc7643tg3ok511fssu6b2j.apps.googleusercontent.com',
    iosBundleId: 'com.sts.userApp',
  );
}
